"""remove active state

Revision ID: 19c42e4d72ba
Revises: af94a57047f8
Create Date: 2026-05-22 21:33:59.855655

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '19c42e4d72ba'
down_revision: Union[str, Sequence[str], None] = 'af94a57047f8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_states')
    op.drop_constraint(op.f('chat_sessions_active_state_id_fkey'), 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'active_state_id')
    op.drop_constraint(op.f('memories_state_id_fkey'), 'memories', type_='foreignkey')
    op.drop_column('memories', 'state_id')
    op.drop_constraint(op.f('messages_state_id_fkey'), 'messages', type_='foreignkey')
    op.drop_column('messages', 'state_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('messages', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('messages_state_id_fkey'), 'messages', 'chat_states', ['state_id'], ['id'])
    op.add_column('memories', sa.Column('state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('memories_state_id_fkey'), 'memories', 'chat_states', ['state_id'], ['id'])
    op.add_column('chat_sessions', sa.Column('active_state_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('chat_sessions_active_state_id_fkey'), 'chat_sessions', 'chat_states', ['active_state_id'], ['id'])
    op.create_table('chat_states',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('session_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('parent_state_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['parent_state_id'], ['chat_states.id'], name=op.f('chat_states_parent_state_id_fkey')),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], name=op.f('chat_states_session_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('chat_states_pkey'))
    )
    # ### end Alembic commands ###
