"""add chat states

Revision ID: 514edc6a947d
Revises: 7a8b5373a658
Create Date: 2026-05-22 16:28:09.679906

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '514edc6a947d'
down_revision: Union[str, Sequence[str], None] = '7a8b5373a658'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chat_states',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.Integer(), nullable=True),
    sa.Column('parent_state_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['parent_state_id'], ['chat_states.id'], ),
    sa.ForeignKeyConstraint(['session_id'], ['chat_sessions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('memories', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'memories', 'chat_states', ['state_id'], ['id'])
    op.add_column('messages', sa.Column('state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'messages', 'chat_states', ['state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'messages', type_='foreignkey')
    op.drop_column('messages', 'state_id')
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.drop_column('memories', 'state_id')
    op.drop_table('chat_states')
    # ### end Alembic commands ###
