"""add memory retrieval fields

Revision ID: 7a8b5373a658
Revises: 0edea751a390
Create Date: 2026-05-20 19:20:20.435816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7a8b5373a658'
down_revision: Union[str, Sequence[str], None] = '0edea751a390'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('memories', sa.Column('last_accessed_at', sa.DateTime(), nullable=True))
    op.add_column('memories', sa.Column('decay_score', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('memories', 'decay_score')
    op.drop_column('memories', 'last_accessed_at')
    # ### end Alembic commands ###
