"""add active state

Revision ID: af94a57047f8
Revises: 514edc6a947d
Create Date: 2026-05-22 20:29:57.362632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'af94a57047f8'
down_revision: Union[str, Sequence[str], None] = '514edc6a947d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_sessions', sa.Column('active_state_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'chat_sessions', 'chat_states', ['active_state_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'chat_sessions', type_='foreignkey')
    op.drop_column('chat_sessions', 'active_state_id')
    # ### end Alembic commands ###
